apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo # name of statefulset
  labels:
    app: mongo # label to track container, so make sure this label is fullfilled on `spec.template.metadata.labels`
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:6.0
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: mongo-config
              mountPath: /etc/mongo
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: mongo-config
          configMap:
            name: mongo-config
            items:
              - key: mongo.conf
                path: mongod.conf
