apiVersion: v1
kind: Service
metadata:
  name: karsajobsserver
spec:
  type: NodePort # type default ClusterIP is okay if we use port-forward, cause we need some issue on M1 with NodePort
  ports:
  - port: 8080 # grep pod port
  selector:
    app: karsajobsserver # grep pod label with key `app`
