apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order
spec:
  hosts:
    - "*" # from all host
  gateways:
    - order-gateway # gateway came from
  http:
    - match:
        - uri:
            exact: /order
      route:
        - destination:
            host: order
            subset: v1
          weight: 90 # v1 with percentage 90%
        - destination:
            host: order
            subset: v2
          weight: 10 # v2 with percentage 10%
