version: 2.1

#  - lint_dockerfile berisi proses untuk menginstal hadolint dan menjalankannya terhadap berkas Dockerfile.
#  - test_app berisi perintah untuk menjalankan unit test untuk backend dengan perintah: go test -v -short --count=1 $(go list ./...)
#  - build-app-karsajobs berisi perintah untuk build dan push image.

jobs:
  lint_dockerfile:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      # enable this when use image docker
      # - run: # https://github.com/google/cadvisor/issues/1131
      #     name: Update ca sertificate and ssl
      #     command: |
      #       apk add --update ca-certificates openssl \
      #         && update-ca-certificates
      - run:
          name: Install hadolint
          command: |
            wget -O /tmp/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            chmod +x /tmp/hadolint
      - run:
          name: Run hadolint
          command: /tmp/hadolint Dockerfile
  test_app:
    description:
      ref https://circleci.com/blog/continuous-integration-for-go-applications
    docker:
      - image: cimg/go:1.17
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v -short --count=1 $(go list ./...)
  build_app_karsajobs:
    description: build docker image and push to ghcr.io
    working_directory: ~/app
    docker:
      - image: docker:24.0.2-alpine3.18
    steps:
      - checkout
      - run: ./build_push_image_karsajobs.sh

workflows:
  lint_test_build:
    jobs:
      - lint_dockerfile
      - test_app:
          requires:
            - lint_dockerfile
      - build_app_karsajobs:
          requires:
            - test_app
