version: 2.1

#  - lint-dockerfile berisi proses untuk menginstal hadolint dan menjalankannya terhadap berkas Dockerfile.
#  - test-app berisi perintah untuk menjalankan unit test untuk backend dengan perintah: go test -v -short --count=1 $(go list ./...)
#  - build-app-karsajobs berisi perintah untuk build dan push image.

jobs:
  lint-dockerfile:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git # https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update ca sertificate and ssl # https://github.com/google/cadvisor/issues/1131
          command: |
            apk add --update ca-certificates openssl \
              && update-ca-certificates
      # Install hadolint
      - run:
          name: Install hadolint
          command: |
            wget -O /tmp/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            chmod +x /tmp/hadolint
            sudo mv /tmp/hadolint /usr/local/bin/
      - run:
          name: Run hadolint
          command: hadolint Dockerfile

workflows:
  lint_test_build:
    jobs:
      - lint-dockerfile

